import Head from "next/head";
import { Header } from "../../../modules/Header";
import { Container } from "../../../modules/shared";
import { Footer } from "../../../modules/Footer";
import ProjectList from "../../../modules/ProjectList";
import { Spacer } from "../../../modules/shared";
import { GetServerSideProps, GetStaticProps, NextPage } from "next";
import { IAPIProject } from "../../../types";
import { useState } from "react";
import { PopUp } from "../../../modules/PopUp";

export const getServerSideProps: GetServerSideProps = async (context: any) => {
  const projects = await fetch(`http://217.197.0.155/data/projects`).then(
    (data) => data.json()
  );

  return {
    props: {
      projects,
    },
  };
};

interface ProjectsProps {
  projects: IAPIProject[];
}

const AdminProjects: NextPage<ProjectsProps> = ({ projects }) => {
  const [popUpActive, setPopUpActive] = useState(false);
  return (
    <>
      <Head>
        <title>Проекты | Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header popUpSetActive={setPopUpActive} logoColor="blue" />
      <PopUp active={popUpActive} setActive={setPopUpActive} />
      <Spacer axis="vertical" size={50} />
      <Container>
        <ProjectList projects={projects} type="admin" />
      </Container>
      <Footer footerColor="pink" />
    </>
  );
};

export default AdminProjects;
