import Head from "next/head";
import Header from "../../components/Header";
import Container from "../../components/Container";
import Footer from "../../components/Footer";
import ProjectList from "../../components/ProjectList";
import Spacer from "../../components/Spacer";
import { GetStaticProps, NextPage } from "next";
import { Filters } from "../../components/ProjectList/Filters";
import { IAPIProject } from "../../types/types";

export const getStaticProps: GetStaticProps = async (context: any) => {
  const projects = await fetch(`http://localhost:3000/api/projects`).then(
    (data) => data.json()
  );

  return {
    props: {
      projects,
    },
    revalidate: 60,
  };
};

interface ProjectsProps {
  projects: IAPIProject[];
}

const Projects: NextPage<ProjectsProps> = ({ projects }) => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Spacer axis="vertical" size={50} />
      <Container>
        <ProjectList projects={projects} />
      </Container>
      <Footer />
    </>
  );
};

export default Projects;
