import { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Header } from "../../modules/Header";
import { Footer } from "../../modules/Footer";
import { Container, Spacer } from "../../modules/shared";
import { Metrics } from "../../modules/Metrics";
import {
  getProjectCommits,
  getProjects,
} from "../../modules/shared/lib/projects";
import { IAPICommit } from "../../types";

export const getStaticPaths: GetStaticPaths = async () => {
  const projects = await getProjects();

  const paths = projects
    .filter((project) => project.projectId !== undefined)
    .map((project) => {
      return {
        params: { id: "" + project.projectId! },
      };
    });

  return { paths, fallback: "blocking" };
};

export const getStaticProps: GetStaticProps = async (context: any) => {
  const commits = await getProjectCommits(context.params.id);

  return {
    props: {
      commits,
    },
    revalidate: 60,
  };
};

interface MetricsPageProps {
  commits: IAPICommit[];
}

const MetricsPage: NextPage<MetricsPageProps> = ({ commits }) => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Spacer axis="vertical" size={30} />
      <Container>
        <Metrics commits={commits} />
      </Container>
      <Footer />
    </>
  );
};

export default MetricsPage;
