import { NextPage } from "next";
import Head from "next/head";
import { Header } from "../../modules/Header";
import { Footer } from "../../modules/Footer";

interface MetricsPageProps {}

const MetricsPage: NextPage<MetricsPageProps> = () => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Footer />
    </>
  );
};

export default MetricsPage;
