import Head from "next/head";
import { Header } from "../../../modules/Header";
import { Footer } from "../../../modules/Footer";

import { GetServerSideProps, NextPage } from "next";
import { AdminEditProject } from "../../../modules/AdminEditProject";
import { Spacer } from "../../../modules/shared";
import {
  getProject,
  getSupervisors,
  getTags,
} from "../../../modules/shared/lib/projects";
import {
  IAPIClient,
  IAPICurator,
  IAPIProject,
  IAPIStatus,
  IAPIStudent,
  IAPISupervisor,
  IAPITag,
} from "../../../types";
import { getStudents } from "../../../modules/shared/lib/students";

export const getServerSideProps: GetServerSideProps = async (context: any) => {
  const projectFetch = getProject(context.params.id);
  const tagsFetch = getTags();
  const supervisorFetch = getSupervisors();
  const studentsFetch = getStudents();

  const [project, tags, supervisorData, students] = await Promise.all([
    projectFetch,
    tagsFetch,
    supervisorFetch,
    studentsFetch,
  ]);

  return {
    props: {
      project,
      tags,
      supervisorData,
      students,
    },
  };
};

interface HomeProps {
  project: IAPIProject;
  tags: IAPITag[];
  supervisorData: [IAPIClient[], IAPICurator[], IAPISupervisor[]];
  students: IAPIStudent[];
}

const ProjectAdmin: NextPage<HomeProps> = ({
  project,
  tags,
  supervisorData,
  students,
}) => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header logoColor="blue" type="admin" />
      <Spacer axis="vertical" size={40} />
      {project && (
        <AdminEditProject
          project={project}
          tags={tags}
          supervisorData={supervisorData}
          students={students}
        />
      )}
      <Footer footerColor="pink" />
    </>
  );
};

export default ProjectAdmin;
