import Head from "next/head";
import { Header } from "../../../modules/Header";
import { Footer } from "../../../modules/Footer";

import { GetServerSideProps, NextPage } from "next";
import { AdminEditProject } from "../../../modules/AdminEditProject";
import { Spacer } from "../../../modules/shared";
import {
  getProject,
  getSupervisors,
  getTags,
} from "../../../modules/shared/lib/projects";
import {
  IAPIClient,
  IAPICurator,
  IAPIProject,
  IAPISupervisor,
  IAPITag,
} from "../../../types";

export const getServerSideProps: GetServerSideProps = async (context: any) => {
  const projectFetch = getProject(context.params.id);
  const tagsFetch = getTags();
  const supervisorFetch = getSupervisors();

  const [project, tags, supervisorData] = await Promise.all([
    projectFetch,
    tagsFetch,
    supervisorFetch,
  ]);

  return {
    props: {
      project,
      tags,
      supervisorData,
    },
  };
};

interface HomeProps {
  project: IAPIProject;
  tags: IAPITag[];
  supervisorData: [IAPIClient[], IAPICurator[], IAPISupervisor[]];
}

const ProjectAdmin: NextPage<HomeProps> = ({
  project,
  tags,
  supervisorData,
}) => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header logoColor="blue" />
      <Spacer axis="vertical" size={40} />
      <AdminEditProject
        project={project}
        tags={tags}
        supervisorData={supervisorData}
      />
      <Footer footerColor="pink" />
    </>
  );
};

export default ProjectAdmin;
