import Head from "next/head";
import { Header } from "../../modules/Header";
import { Footer } from "../../modules/Footer";

import { NextPage } from "next";
import { Container, Spacer } from "../../modules/shared";
import { AdminTeamList } from "../../modules/AdminTeamList";

interface HomeProps {}

const TeamsAdmin: NextPage<HomeProps> = () => {
  /*
  formDataRef надо будет передавать во все компоненты, чтобы отрендерить
  начальные данные, которые нам приходят с бекенда

  Когда админ будет что-то менять в ваших компонентах, помимо
  стейта своего компонента вы будете менять и соответствующее свойство этого рефа

  Нужно это, чтобы при нажатии на кнопку "Сохранить изменения", которая в этом файле
  будет находиться, сразу в готовом виде была информация, которую нужно отправлять бекенду

  Сейчас formDataRef использует от руки набранные данные,
  вы тоже набирайте их вручную, пока мы не настроили работу с бекендом
  По-хорошему мы будем делать запрос серверу и через getStaticProps/getServerSideProps
  передавать пропом то, что нам подкинет бекенд
  */

  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header logoColor="blue"/>
      <Spacer axis="vertical" size={40} />
      <Container>
        <AdminTeamList />
      </Container>
      <Footer footerColor='pink'/>
    </>
  );
};

export default TeamsAdmin;
