import Head from "next/head";
import Header from "../../components/Header/";
import TagSliderForCurProject from "../../components/TagSliderForCurProject/";
import Container from "../../components/Container";
import Footer from "../../components/Footer";
import Spacer from "../../components/Spacer";
import ProjectPublicAboutUs from "../../components/ProjectPublicAboutUs"
import { NextPage } from "next";


interface HomeProps { }

const Home: NextPage<HomeProps> = () => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Spacer axis="vertical" size={40} />



      <Spacer axis="vertical" size={40} />
      <Container>
        <TagSliderForCurProject />
      </Container>
      <Spacer axis="vertical" size={40} />

      <ProjectPublicAboutUs />

      <Footer />
    </>
  );
};

export default Home;
