import Head from 'next/head';
import Header from '../../components/Header/';
import TagSliderForCurProject from '../../components/ProjectPagePublicPath/TagSliderForCurProject';
import AboutProject from '../../components/ProjectPagePublicPath/Contener4CuTuDi&PridjectDescr/AboutProject';
import InfoAboutCuTuDi from '../../components/ProjectPagePublicPath/Contener4CuTuDi&PridjectDescr/InfoAboutCustomerTutorDirector';
import Container from '../../components/Container';
import Footer from '../../components/Footer';
import Spacer from '../../components/Spacer';
import ProjectPublicAboutUs from '../../components/ProjectPublicAboutUs';
import { NextPage } from 'next';
import DateBlock from '../../components/ProjectPagePublicPath/DateBlock';
import Contener4CuTuDiPridjectDescr from '../../components/ProjectPagePublicPath/Contener4CuTuDi&PridjectDescr';


interface HomeProps {}

const Home: NextPage<HomeProps> = () => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Spacer axis='vertical' size={40} />

      <Spacer axis='vertical' size={40} />
      <Container>
        <TagSliderForCurProject />
      
      <Spacer axis='vertical' size={40} />

      <ProjectPublicAboutUs />

      <DateBlock
        dateOfCreate='11.10.2011'
        dateOfRegister='11.10.2011 - 21.10.2012'
        deadline='11.10.2011 - 21.10.2012'
        status='открыт'
      />
      <Contener4CuTuDiPridjectDescr/>
      {/* <Container>
        <InfoAboutCuTuDi />
        <AboutProject />
      </Container> */}
      <Spacer axis='vertical' size={40} />
      </Container>
      <Footer />
    </>
  );
};

export default Home;
