import Head from "next/head";
import Header from "../components/Header/";
import FirstInfo from "../components/FirstInfo/";
import ClinicCard from "../components/ClinicCard/";
import TagSlider from "../components/TagSlider";
import Container from "../components/Container";
import ForClient from "../components/ForClient";
import Footer from "../components/Footer";
import FormForClient from "../components/FormForClient";
import ProjectList from "../components/ProjectList";
import ClinicSlider from "../components/ClinicSlider";
import Spacer from "../components/Spacer";
import { NextPage } from "next";
import HomeProjectList from "../components/HomeProjectList";
import TagFilter from "../components/TagFilter";
import TempTagContainer from "../components/TempTagContainer";
import YearFilter from "../components/YearFilter";
import MainPageBg from "../components/MainPageBg";
import { Filters } from "../components/ProjectList/Filters";
import PopUp from "../components/PopUp";
import { useState } from "react";

interface HomeProps {}

const Home: NextPage<HomeProps> = () => {

  const [popUpActive, setPopUpActive] = useState(true);

  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header popUpSetActive={setPopUpActive}/>
      <PopUp active={popUpActive} setActive={setPopUpActive}/>
      <Spacer axis="vertical" size={40} />
      <Container>
        <FirstInfo />
      </Container>
      <MainPageBg image={"/clinic-slider-bg.svg"}>
        <Container>
          <ClinicSlider />
        </Container>
      </MainPageBg>
      <Spacer axis="vertical" size={40} />
      <Container>
        <TagSlider />
      </Container>
      <Spacer axis="vertical" size={40} />
      <MainPageBg image={"/mainpage-projects-bg.svg"}>
        <Container>
          <HomeProjectList />
        </Container>
      </MainPageBg>
      <Spacer axis="vertical" size={40} />
      <Container>
        <ForClient />
      </Container>
      <Spacer axis="vertical" size={40} />
      <Footer />
    </>
  );
};

export default Home;
