import Head from "next/head";
import Header from "../components/Header/";
import FirstInfo from "../components/FirstInfo/";
import ClinicCard from "../components/ClinicCard/";
import TagSlider from "../components/TagSlider";
import Container from "../components/Container";
import ForClient from "../components/ForClient";
import Footer from "../components/Footer";
import FormForClient from "../components/FormForClient";
import ProjectList from "../components/ProjectList";
import ClinicSlider from "../components/ClinicSlider";
import Spacer from "../components/Spacer";
import { NextPage } from "next";
import HomeProjectList from "../components/HomeProjectList";

interface HomeProps { }

const Home: NextPage<HomeProps> = () => {
  return (
    <>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Spacer axis="vertical" size={100} />
      <Container>
        <FirstInfo />
        <Spacer axis="vertical" size={50} />
        <ClinicSlider />
        <Spacer axis="vertical" size={50} />
        <TagSlider />
        <Spacer axis="vertical" size={50} />
        <ForClient />
      </Container>
      <HomeProjectList />
      <Footer />

      <FormForClient stylesProp={{ width: "100%", height: "60vh" }} />

      <ProjectList />
    </>
  );
};

export default Home;
