import Head from "next/head";
import Header from "../components/Header/index";
import FistInfo from "../components/FistInfo/index";
import ProjectCard from "../components/ProjectCard/index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      <FistInfo/>
      <ProjectCard/>
    </div>
  );
}
