import Head from "next/head";
import { Header } from "../../modules/Header";
import { Container } from "../../modules/shared";
import { Footer } from "../../modules/Footer";
import FormForClient from "../../modules/FormForClient";
import { Spacer } from "../../modules/shared";
import { NextPage } from "next";

interface ClientFormProps {}

const ClientForm: NextPage<ClientFormProps> = () => {
  return (
    <div>
      <Head>
        <title>Реестр проектов СПбГУ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Spacer axis="vertical" size={50} />
      <Container>
        <FormForClient stylesProp={{ width: "100%", height: "80vh" }} />
      </Container>
      <Footer />
    </div>
  );
};

export default ClientForm;
